title: Marching West
description: Una experiencia RPG masiva
collections:
  marchers:
    output: true
  challenges:
    output: false
exclude:
  - 'Gemfile*'
  - 'node_modules'
  - 'package*.json'
  - 'webpack.config.js'
  - '_src'
google_analytics: 'UA-117519957-1'
plugins:
  - jekyll-seo-tag
